# Generated by Django 4.1.5 on 2023-03-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('schemeid', models.CharField(max_length=20)),
                ('schemename', models.CharField(max_length=100)),
                ('ministry', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=2000)),
                ('benefits', models.CharField(max_length=2000)),
                ('application', models.CharField(max_length=5000)),
                ('state', models.CharField(max_length=500)),
                ('documentsrequired', models.CharField(max_length=5000)),
            ],
        ),
    ]
