# Generated by Django 4.1.5 on 2023-03-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Registration_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('emailid', models.CharField(max_length=200)),
                ('phoneno', models.CharField(max_length=100)),
                ('fulladdress', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=100)),
                ('mstatus', models.CharField(max_length=100)),
                ('aor', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('ph', models.CharField(max_length=50)),
                ('minority', models.CharField(max_length=50)),
                ('student', models.CharField(max_length=50)),
                ('empstatus', models.CharField(max_length=50)),
                ('currempstatus', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('annualincome', models.CharField(max_length=50)),
            ],
        ),
    ]
