# Generated by Django 4.1.5 on 2023-03-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_user_registration_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eligibility_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemeid', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('mstatus', models.CharField(max_length=100)),
                ('mage', models.CharField(max_length=50)),
                ('maxage', models.CharField(max_length=50)),
                ('aor', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=100)),
                ('ph', models.CharField(max_length=50)),
                ('minority', models.CharField(max_length=50)),
                ('student', models.CharField(max_length=50)),
                ('empstatus', models.CharField(max_length=50)),
                ('currempstatus', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('annualincome', models.CharField(max_length=50)),
            ],
        ),
    ]
